# Generated by Django 5.1.7 on 2025-03-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_remove_userprofile_name_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
