# Generated by Django 5.1.7 on 2025-03-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
