# Generated by Django 5.1.7 on 2025-03-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='facts',
        ),
    ]
